# Generates benchmarks/30k_variables.rb: a benchmark with 30k local variables
# spread across methods that read and write them back and forth.
#
# Most assignments are variable-to-variable copies. Every MIX_EVERY-th
# assignment mixes in another live variable with ^ or (+ ... & mask), tracking
# value identities so that no operation ever combines two copies of the same
# value. This keeps the data flow irreducible: the mixes cannot be folded away
# algebraically by any compiler, while the copies in between reward compilers
# that can see through local variable shuffling.
#
# Usage: ruby misc/gen_30k_variables.rb [num_methods] [vars_per_method] [rounds]

num_methods = Integer(ARGV[0] || 300)
vars_per_method = Integer(ARGV[1] || 100)
rounds = Integer(ARGV[2] || 3)

MIX_EVERY = 10
MIX_WINDOW = 25
MASK = 4095

rng = Random.new(42)
out = +""
out << "# frozen_string_literal: true\n"
out << "# Generated by misc/gen_30k_variables.rb: #{num_methods} methods x #{vars_per_method} local variables = #{num_methods * vars_per_method} local variables\n"
out << "require_relative '../harness/loader'\n\n"

num_methods.times do |m|
  out << "def fun_l0_n#{m}(x)\n"
  out << "  v0 = x\n"
  # val[i] tracks which abstract value v{i} currently holds, so that a mix
  # never combines a value with a copy of itself (e.g. x ^ x).
  val = Array.new(vars_per_method)
  val[0] = 0
  next_val = 1
  mix_count = 0
  emit = lambda do |dst, src|
    out << "  v#{dst} = v#{src}\n"
    val[dst] = val[src]
  end
  mix = lambda do |dst, src, indices|
    candidates = indices.select { |c| val[c] && val[c] != val[src] }
    if candidates.empty?
      emit.call(dst, src)
    else
      j = candidates[rng.rand(candidates.size)]
      if (mix_count += 1).odd?
        out << "  v#{dst} = v#{src} ^ v#{j}\n"
      else
        out << "  v#{dst} = (v#{src} + v#{j}) & #{MASK}\n"
      end
      val[dst] = next_val
      next_val += 1
    end
  end
  # Seed a few distinct values so that the mixes always have two different
  # values to combine.
  (1..3).each do |k|
    out << "  v#{k} = (v#{k - 1} + #{m * 31 + k * 7 + 1}) & #{MASK}\n"
    val[k] = next_val
    next_val += 1
  end
  rounds.times do |r|
    if r.even?
      # forward pass: shift values up, mixing in a recent variable every MIX_EVERY steps
      start = r.zero? ? 4 : 1
      (start...vars_per_method).each do |i|
        if i % MIX_EVERY == 0
          mix.call(i, i - 1, ([0, i - MIX_WINDOW].max..(i - 2)).to_a)
        else
          emit.call(i, i - 1)
        end
      end
    else
      # backward pass: shift values down again
      (0..(vars_per_method - 2)).to_a.reverse.each do |i|
        if i % MIX_EVERY == 0
          mix.call(i, i + 1, ((i + 2)..[i + MIX_WINDOW, vars_per_method - 1].min).to_a)
        else
          emit.call(i, i + 1)
        end
      end
    end
  end
  ret = rounds.even? ? "v0" : "v#{vars_per_method - 1}"
  out << "  #{ret}\n"
  out << "end\n\n"
end

out << "INTERNAL_ITRS = Integer(ENV.fetch(\"INTERNAL_ITRS\", 2000))\n\n"
out << "run_benchmark(20) do\n"
out << "  s = 0\n"
out << "  x = 0\n"
out << "  i = 0\n"
out << "  while i < INTERNAL_ITRS\n"
out << "    x = (x + 1) & 0xff\n"
num_methods.times do |m|
  out << "    s ^= fun_l0_n#{m}(x)\n"
end
out << "    i += 1\n"
out << "  end\n"
out << "  s\n"
out << "end\n"

File.write(File.expand_path("../benchmarks/30k_variables.rb", __dir__), out)
puts "Wrote benchmarks/30k_variables.rb (#{num_methods} methods x #{vars_per_method} vars, #{rounds} rounds)"
